### ISSUE TITLE
Sample of annotations to be provided in prisma scema model

### ISSUE THREAD

**Issue by ghost** [LCozzoli/PrismaEncrypter#1]
Can we get sample for the annotations and working tests examples for this package?

**Comment by LCozzoli** [comment]
Hello, there is no annotations in the prisma schema implemented yet, Prisma doesn't offer schema extensions yet, the only way can be to parse the documentation "///" of fields and store something there

I pushed a little example for you :
https://github.com/LCozzoli/PrismaEncrypter/tree/main/examples/simple

**Comment by ghost** [comment]
Thanks for the sample.
