### ISSUE TITLE
Facing error "Cannot read properties of undefined (reading 'key')"

### ISSUE THREAD

**Issue by ghost** [LCozzoli/PrismaEncrypter#2]
I tried to run a basic sample but I am getting this error: "Cannot read properties of undefined (reading 'key')"

Here is the code:
`
const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient();
const { encryptionMiddleware } = require('prisma-encrypter');

prisma.$use(
  encryptionMiddleware({
    global: {
      key: 'Xp2r5u8x/A?DcG+KbPeShVmYq3t6v9y$',
    },
    models: [
      {
        model: 'User',
        fields: ['email']
      },
    ],
  })
);

  async function main() {
    const newUser = await prisma.user.create({
        data: {
          name: 'Alice2',
          email: 'alice2@prisma.io',
        },
      })
      console.log('users: ', users);
  }
  
  main().catch(console.error)
`

Though the user gets created in the database and email is in the encrypted format. But why this error keeps on happening?

**Comment by LCozzoli** [comment]
Are you using the latest version ?
`npm i prisma-encrypter@latest`
I fixed a little issue when using global key in my latest version

**Comment by ghost** [comment]
Yes, I have tried to install latest prisma-encrypter. Here is the content of package.json:

`{
  "dependencies": {
    "@prisma/client": "^4.4.0",
    "prisma-encrypter": "^0.0.5"
  },
  "devDependencies": {
    "prisma": "^4.4.0",
    "typescript": "^4.8.4"
  }
}
`

Now getting this output:
`decrypt email alice@prisma.io The argument 'encoding' is invalid for data of length 15. Received 'hex'
decrypt email alice1@prisma.io error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
`

**Comment by LCozzoli** [comment]
Are you running your tests with an empty database? this error can happen when the decryption key is wrong or data is not encrypted in the db, is it when creating the entry?

**Comment by ghost** [comment]
Got it, yeah some of the user emails were created before adding encryption and were in plain text. I removed them and tried. it is working fine now. 

Thanks.
